//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinelist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booklist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public booklist()
        {
            this.carts = new HashSet<cart>();
        }
    
        public int book_id { get; set; }
        public string book_name { get; set; }
        public string author_name { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> genre_id { get; set; }
    
        public virtual genre genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
    }
}
