//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinelist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int serial_no { get; set; }
        public Nullable<int> book_id { get; set; }
        public string book_name { get; set; }
        public string author_name { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> genre_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual booklist booklist { get; set; }
        public virtual genre genre { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
