//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------





namespace onlinelist.Models
{
    using System;
    using System.Collections.Generic;

    public partial class commonModel
    {
        public LoginDetail LoginDetail { get; set; }

        public UserDetail UserDetail { get; set; }

    }
}
