//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinelist.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class miniprojectEntities : DbContext
    {
        public miniprojectEntities()
            : base("name=miniprojectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<booklist> booklists { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<LoginDetail> LoginDetails { get; set; }
        public virtual DbSet<UserBookDetail> UserBookDetails { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
    }
}
