//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinelist.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public class userDetailsMeta
    {
        [Required(ErrorMessage = "Required")]
        [StringLength(24, ErrorMessage = "Should be less then 24 alphabets")]
        [RegularExpression("^[a-zA-z]+([ ][a-zA-Z]+)*$", ErrorMessage = "Invalid Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Required")]
        [DataType(DataType.EmailAddress)]
        public string EmailId { get; set; }
        [Required(ErrorMessage = "Required")]
        [RegularExpression("^[0-9]{10}", ErrorMessage = "Invalid Phone No.")]
        public Nullable<long> Phone_no { get; set; }
    }

    [MetadataType(typeof(userDetailsMeta))]

    public partial class UserDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDetail()
        {
            this.carts = new HashSet<cart>();
            this.UserBookDetails = new HashSet<UserBookDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> LoginID { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public Nullable<long> Phone_no { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
        public virtual LoginDetail LoginDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBookDetail> UserBookDetails { get; set; }
    }
}
